# Handling Reading
exclude: [Gemfile, README.md, run.bat]

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Outputting
baseurl: /notes
timezone: America/California

sass:
  style: compressed

# Custom
domain: cwmonkey.github.com
url: /notes
title: notes
description: Take some notes
copyright: 2017
name: Notes
author: cwmonkey
twitter:
  username: WrasslorMonkey
github:
  username: cwmonkey
javascripts:
  - src: js/vendor/jquery/3.1.1/jquery.min.js
  - src: js/vendor/showdown/1.6.4/showdown.min.js
  - src: js/Imgur.js
  - src: js/vendor/moment.js/2.17.1/moment.min.js
  - src: js/vendor/clipboard.js/1.6.0/clipboard.min.js
  - src: js/ImageClipboard.js
  - src: js/Tpl.js
  - src: js/jquery.serializeObject.js
  - src: js/GoogleDriveAPI.js
  - src: js/Thing.js
  - src: js/Thing.Note.js
  - src: js/Thing.Preference.js
  - src: js/Thing.Category.js
  - src: js/ThingCollection.js
  - src: js/notes.js
